server:
  port: 8081

---
spring:
  profiles:
    active: jms-listener #jms-template 
  jms:
    template:
      receive-timeout: 2
  artemis:
    broker-url: tcp://127.0.0.1:61616
    user:
    password:
    embedded:
      enabled: false
    
---
spring:
  profiles:
    active: kafka-listener
    
  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    consumer:
#      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacocloud_kitchen
      properties:
#        spring.json.value.default.type: tacos.dto.TacoOrderDto
        spring.json.trusted.packages: tacos.dto
